FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production \
    APP_VERSION=2.3.9 \
    GMIR_ALLOWED_ORIGINS=https://bbblaprk-svg.github.io \
    LS_OPENAPI_ENABLED=true \
    LS_NEWS_ENABLED=true \
    LS_NEWS_WS_URL=wss://openapi.ls-sec.co.kr:9443/websocket \
    LS_NEWS_TR_KEY=NWS001 \
    LS_DEEP_NEWS_ENABLED=true \
    LS_DEEP_NEWS_BODY_ENABLED=true \
    LS_DEEP_NEWS_MIN_IMPORTANCE=55 \
    LS_T3102_SCHEMA_PROBE=true \
    LS_T3102_MIN_INTERVAL_MS=1250 \
    LS_REALTIME_ENABLED=true \
    LS_REALTIME_WS_URL=wss://openapi.ls-sec.co.kr:9443/websocket \
    LS_REALTIME_STREAMS=US3,UH1,UPH \
    LS_REALTIME_MAX_TARGETS=20 \
    LS_REALTIME_FRESH_PACKET_MS=15000 \
    LS_REALTIME_STALL_RECOVERY_MS=20000 \
    LS_REALTIME_RECOVERY_COOLDOWN_MS=15000 \
    LS_REALTIME_BOOK_RETAIN_MS=180000 \
    LS_RUNTIME_RANK_TICK_MS=2000 \
    LS_RUNTIME_INGEST_TICK_MS=2000 \
    LS_RUNTIME_CORE_SUB_REFRESH_MS=15000 \
    LS_RUNTIME_CORE_EVAL_MAX=35 \
    LS_RUNTIME_CORE_CHALLENGERS=20 \
    LS_RUNTIME_CORE_WS_MAX=20 \
    LS_RUNTIME_CORE_WS_CHALLENGERS=5 \
    LS_RUNTIME_WS_FRESH_FOR_REST_MS=3000 \
    LS_RUNTIME_BOOTSTRAP_MIN_COVERAGE=0.75 \
    LS_RUNTIME_BOOTSTRAP_MIN_USABLE=2000 \
    LS_FULL_MARKET_ENABLED=true \
    LS_MARKET_SCAN_MAX_UNIVERSE=3200 \
    LS_FULL_MARKET_LIVE_SHARD_SIZE=400 \
    LS_FULL_MARKET_BOOTSTRAP_SHARD_SIZE=800 \
    LS_FULL_MARKET_BOOTSTRAP_FILL_COVERAGE=0.75 \
    LS_FULL_MARKET_BOOTSTRAP_SCAN_CACHE_MS=1000 \
    LS_FULL_MARKET_HOT_LANE_SIZE=300 \
    LS_FULL_MARKET_HOT_LANE_INTERVAL_MS=5000 \
    LS_FULL_MARKET_LIVE_STALE_MS=100000 \
    LS_FULL_MARKET_LIVE_MIN_COVERAGE=0.75 \
    LS_FULL_MARKET_MIN_MASTER=500 \
    LS_BROAD_FRESH_MS=15000 \
    LS_BROAD_USABLE_MS=30000 \
    LS_MULTI_QUOTE_BATCH=50 \
    LS_MULTI_QUOTE_BATCH_DELAY_MS=0 \
    LS_MARKET_SCAN_CACHE_MS=5000 \
    LS_CLOSED_BATCH_DELAY_MS=0 \
    LS_API_GLOBAL_CONCURRENCY=6 \
    LS_API_BUDGET_QUEUE_MAX=120 \
    LS_API_T8407_RPS=4.0 \
    LS_API_T8450_RPS=8.0 \
    LS_API_T1301_RPS=1.7 \
    LS_API_T1101_RPS=4.0 \
    LS_API_T1302_RPS=0.9 \
    LS_API_T1102_RPS=4.0 \
    LS_API_T9945_RPS=1.5 \
    LS_UNIFIED_T8450_ENABLED=true \
    LS_UNIFIED_T8450_CACHE_MS=4000 \
    LS_UNIFIED_T8450_MAX_TARGETS=20 \
    LS_UNIFIED_T8450_CALL_GAP_MS=0 \
    LS_UNIFIED_T8450_QUEUE_MAX=72 \
    LS_T8450_WORKERS=3 \
    LS_T8450_MEMBER_DEADLINE_MS=5000 \
    LS_T8450_CHALLENGER_DEADLINE_MS=15000 \
    LS_T8450_DISCOVERY_DEADLINE_MS=30000 \
    LS_UNIFIED_MEMBER_FRESH_MS=5000 \
    LS_UNIFIED_CHALLENGER_FRESH_MS=15000 \
    LS_UNIFIED_LIVE_STALE_MS=30000 \
    LS_LIVE_REST_WORKER_GAP_MS=600 \
    LS_LIVE_REST_QUEUE_MAX=30 \
    LS_LIVE_REST_FRESH_MS=10000 \
    LS_LIVE_REST_STALE_MS=30000 \
    LS_LIVE_REST_MEMBER_DEADLINE_MS=10000 \
    LS_LIVE_REST_CHALLENGER_DEADLINE_MS=20000 \
    LS_NXT_DISCOVERY_ENABLED=true \
    LS_NXT_DISCOVERY_CACHE_MS=15000 \
    LS_NXT_DISCOVERY_MAX_TARGETS=80 \
    LS_NXT_DISCOVERY_FEED_WINDOW=36 \
    LS_NXT_DISCOVERY_KEEP=50 \
    LS_NXT_DISCOVERY_STALE_MS=90000 \
    LS_NXT_WATCH_ENABLED=true \
    LS_NXT_WATCH_RECHECK_MS=12000 \
    LS_NXT_WATCH_MAX=20 \
    LS_NXT_WATCH_ENTRY_SCORE=55 \
    LS_NXT_WATCH_HOLD_SCORE=45 \
    LS_NXT_WATCH_WEAK_LIMIT=2 \
    LS_NXT_WATCH_STALE_MS=60000 \
    LS_NXT_WATCH_DEADLINE_MS=10000 \
    LS_CIRCUIT_BREAKER_THRESHOLD=4 \
    LS_CIRCUIT_BREAKER_BASE_MS=3000 \
    LS_CIRCUIT_BREAKER_MAX_MS=30000 \
    LS_RANK_MIN_HOLD_MS=45000 \
    LS_RANK_STALE_REUSE_MS=20000 \
    LS_RANK_DATA_FREEZE_MS=30000 \
    LS_RANK_GLOBAL_GAP_COUNT=4 \
    LS_RANK_CHECKPOINT_MS=45000 \
    PREIGNITION_JOURNAL_FLUSH_MS=45000 \
    LS_SNAPSHOT_CACHE_MS=12000 \
    LS_PREIGNITION_MAX_TARGETS=20 \
    LS_TAPE_ROWS=120 \
    LS_CLOSED_MINUTE_ROWS=30 \
    LS_CLOSED_T1302_INTERVAL_MS=1050 \
    LS_CLOSED_SNAPSHOT_CACHE_MS=1800000 \
    LS_CLOSED_FETCH_RETRIES=2 \
    LS_CLOSED_RETRY_DELAY_MS=1100 \
    LS_CLOSED_PROVISIONAL_RETRY_MS=120000 \
    LS_CLOSED_PENDING_RETRY_MS=60000 \
    LS_CLOSED_MARKET_SCAN_CACHE_MS=1800000 \
    LS_CLOSED_BATCH_RETRIES=2 \
    LS_CLOSED_MIN_SCAN_COVERAGE=1.0 \
    LS_CLOSED_DECISION_CACHE_MS=1800000 \
    LS_CLOSED_MAX_TARGETS=24 \
    LS_MARKET_SCAN_SHORTLIST=40 \
    STORE_DIR=/tmp/kr-news-radar \
    RENDER_FREE_MODE=true \
    OFFICIAL_ONLY_FREE_MODE=true \
    OFFICIAL_FEEDS_ENABLED=true \
    FOREIGN_FIRST_MODE=true \
    ACTIVE_MONITOR_MAX=20 \
    SECTOR_ROTATION_WINDOW_HOURS=18 \
    WEEKEND_PAUSE=false \
    ACCESS_REFRESH_ENABLED=true \
    ACCESS_REFRESH_EMPTY_RETRY_MS=180000 \
    NEWS_VIEW_HOURS=24 \
    NEWS_RETENTION_DAYS=3 \
    SSE_MAX_CONNECTIONS=5 \
    GMIR_RUNTIME_RECOVERY_MAX_AGE_MS=864000000 \
    GMIR_LIVE_RECOVERY_MAX_AGE_MS=64800000 \
    BACKUP_SCHEDULE_ENABLED=false

RUN addgroup -S nodejs && adduser -S radar -G nodejs \
    && mkdir -p /tmp/kr-news-radar \
    && chown -R radar:nodejs /tmp/kr-news-radar /app

COPY GLOBAL_MARKET_IMPACT_RADAR_FINAL_239_CLOSED_BOARD_CONTINUITY.bin /tmp/app.tar.gz
RUN set -eux; \
    tar -xzf /tmp/app.tar.gz -C /app; \
    rm -f /tmp/app.tar.gz; \
    npm ci --omit=dev --no-audit --no-fund; \
    npm run check; \
    chown -R radar:nodejs /app

USER radar
EXPOSE 10000
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 CMD wget -qO- "http://127.0.0.1:${PORT:-10000}/api/health" >/dev/null || exit 1
CMD ["node", "server.js"]
